name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'spotocracy-client' #Must be unique in Heroku
          heroku_email: 'chang.alex@northeastern.edu'
          appdir: '/client'
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'spotocracy-server' #Must be unique in Heroku
          heroku_email: 'chang.alex@northeastern.edu'
          appdir: '/server'
